export const defaultTheme = {
  themeColor: 'rgb(19, 128, 255)',
  activeStrokeColor: 'red',
  hoverStrokeColor: 'green',
  themeColor_sub: 'rgb(245,245,245)',
  themeColor_leaf: 'transparent',
  fontColor_root: '#fff',
  fontColor_sub: '#333',
  fontColor_leaf: '#333',
  branch: 2,
  branchColor: 'rgb(19, 128, 255)',
  scaleRatio: 1,
  radius: 4,
  paddingH: 10,
  paddingV: 10,
  maxFontCount: 12,
  globalFontSize: [16, 14, 12],
  lineType: 'cubic-horizontal',
  placeholderText: '新建模型',
};
export const defaultTools = {
  timetravel: false,
  downloadBtn: false,
  fitBtn: false,
  centerBtn: false,
};
